# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 06:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='freetime',
            old_name='time',
            new_name='time_start',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='free_time',
        ),
        migrations.AddField(
            model_name='freetime',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 10, 22, 6, 59, 18, 485205)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullprofile',
            name='free_time',
            field=models.ManyToManyField(to='studygroups.FreeTime'),
        ),
        migrations.AddField(
            model_name='fullprofile',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Profile'),
        ),
    ]
