# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0002_auto_20161023_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='invited',
            field=models.ManyToManyField(related_name='invited_to', to='studygroups.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='this', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='joined', to='studygroups.Profile'),
        ),
    ]
