# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('R', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('U', 'Sunday')], max_length=1)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='fullprofile',
            name='free_time',
        ),
        migrations.RemoveField(
            model_name='fullprofile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='FreeTime',
        ),
        migrations.DeleteModel(
            name='FullProfile',
        ),
    ]
