# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0003_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studygroups.Course')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='memebers',
            field=models.ManyToManyField(to='studygroups.Profile'),
        ),
    ]
