# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0005_auto_20161022_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='test', upload_to='../static/images'),
            preserve_default=False,
        ),
    ]
