# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0006_auto_20161022_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='memebers',
            new_name='members',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
