# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0007_auto_20161022_2122'),
        ('studygroups', '0004_auto_20161022_1926'),
    ]

    operations = [
    ]
