# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studygroups', '0008_merge_20161022_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateduration',
            name='in_proposed_group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='location',
            field=models.CharField(default='Nowhere', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_time',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='studygroups.DateDuration'),
            preserve_default=False,
        ),
    ]
